### ISSUE TITLE
Line Heights classes were removed from 2.8.0

### ISSUE THREAD

**Issue by AlexandreArpin** [sharegate/tachyons-sg#14]
In commit 2ebfaba8fc9083da69efb7395972dc85c7e7bd5c, classes were removed from Tachyons when they should have been kept along with the new classes.

`lh-solid`, `lh-copy` and `lh-title`

They should be deprecated in 3.0 however :)

**Comment by fraincs** [comment]
Fixed in commit https://github.com/sharegate/tachyons-sg/commit/ec890995220594045e9113d3c3cf66009f7b2f9e
