### ISSUE TITLE
Add class for visibility: hidden

### ISSUE THREAD

**Issue by Guillaume-Docquier** [sharegate/tachyons-sg#9]
It would be useful

**Comment by patricklafrance** [comment]
Est-ce que ça va dans Tachyon ou ça devrait plutôt être dans les projets?

**Comment by joseph-passineau** [comment]
Dans Tachyon d'apres moi.  Les classes atomiques devraient etre dans Tachyons

```
.vh {
    visibility: hidden;
}

.vv {
    visibility: visible;
}
```

**Comment by patricklafrance** [comment]
Oui je comprends sauf qu'il y a probablement une raison si l'auteur de tachyon ne la pas ajouté initialement.

**Comment by joseph-passineau** [comment]
Il ne semble pas y avoir de raison. Seulement que l'auteur de Tachyons n'utilise pas Visibility.
https://github.com/tachyons-css/tachyons/issues/504

**Comment by Guillaume-Docquier** [comment]
On a utilisé une autre méthode
